// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const markerPrefix = "+metrics:conditions:"

// fileTemplate is the Go source template for generated collector files.
// When the concrete type and the ConditionStatus type are from the same package
// (.SamePackage == true), only one import is emitted; otherwise two are emitted.
const fileTemplate = `// Code generated by metrics-gen. DO NOT EDIT.

package operator

import (
	"fmt"

	"github.com/prometheus/client_golang/prometheus"
	"k8s.io/client-go/tools/cache"
{{ if .SamePackage }}
	{{ .TypePkgAlias }} "{{ .TypePkgImport }}"
{{- else }}
	{{ .CondStatusAlias }} "{{ .CondStatusImport }}"
	{{ .TypePkgAlias }} "{{ .TypePkgImport }}"
{{- end }}
)

type conditionCollector struct {
	stores []cache.Store
}

func NewConditionCollector(stores ...cache.Store) prometheus.Collector {
	return &conditionCollector{
		stores: stores,
	}
}

const resourceType = "{{ .ResourceType }}"

var conditionStatuses = []{{ .CondStatusAlias }}.ConditionStatus{
{{- range .ConditionStatuses }}
	{{ $.CondStatusAlias }}.{{ . }},
{{- end }}
}

var conditionDesc = prometheus.NewDesc(
	prometheus.BuildFQName("prometheus_operator", resourceType, "status_condition"),
	fmt.Sprintf("The current status conditions of a %s resource", resourceType),
	[]string{"name", "namespace", "condition", "status"},
	nil,
)

func (cc *conditionCollector) Describe(ch chan<- *prometheus.Desc) {
	ch <- conditionDesc
}

func (cc *conditionCollector) Collect(ch chan<- prometheus.Metric) {
	for _, store := range cc.stores {
		for _, obj := range store.List() {
			o := obj.(*{{ .TypePkgAlias }}.{{ .ConcreteType }})
			if o.DeletionTimestamp != nil {
				continue
			}
			for _, cond := range o.{{ .ConditionsAccessor }} {
				for _, s := range conditionStatuses {
					v := 0
					if cond.Status == s {
						v = 1
					}
					ch <- prometheus.MustNewConstMetric(
						conditionDesc,
						prometheus.GaugeValue,
						float64(v),
						o.Name,
						o.Namespace,
						string(cond.Type),
						string(s),
					)
				}
			}
		}
	}
}
`

type templateData struct {
	ResourceType       string
	ConcreteType       string
	ConditionsAccessor string
	// TypePkgAlias/Import: the package of the concrete resource type (e.g. monitoringv1alpha1).
	TypePkgAlias  string
	TypePkgImport string
	// CondStatusAlias/Import: the package where ConditionStatus is defined (e.g. monitoringv1).
	CondStatusAlias  string
	CondStatusImport string
	// SamePackage is true when TypePkg and CondStatusPkg are the same import.
	SamePackage       bool
	ConditionStatuses []string
}

// markerInfo holds data extracted from a marker-annotated type declaration.
type markerInfo struct {
	ResourceType   string // e.g. "prometheus"
	StructName     string // e.g. "Prometheus"
	ConditionsPath string // e.g. ".status.conditions"
}

// packageInfo holds the parsed state of a Go package directory.
type packageInfo struct {
	dir        string
	importPath string
	// imports maps import alias → full import path for every file in the package.
	imports map[string]string
	// types maps type name → struct AST node for every struct type in the package.
	types map[string]*ast.StructType
	// statuses holds ConditionStatus constant names in declaration order.
	statuses []string
	// files holds the parsed AST files (needed for marker scanning).
	files []*ast.File
}

func main() {
	apiDir := flag.String("api-dir", "", "root of the API module to scan")
	outDir := flag.String("out-dir", "./pkg/metrics", "root directory for generated output packages")
	module := flag.String("module", "", "root Go module path")
	flag.Parse()

	if *apiDir == "" {
		fmt.Fprint(os.Stderr, "metrics-gen: --api-dir must be defined\n")
		os.Exit(1)
	}

	if *module == "" {
		fmt.Fprint(os.Stderr, "metrics-gen: module must be defined\n")
		os.Exit(1)
	}

	absAPIDir, err := filepath.Abs(*apiDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "metrics-gen: resolving api-dir: %v\n", err)
		os.Exit(1)
	}

	absOutDir, err := filepath.Abs(*outDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "metrics-gen: resolving out-dir: %v\n", err)
		os.Exit(1)
	}

	subModulePath, err := readModulePath(filepath.Join(absAPIDir, "go.mod"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "metrics-gen: reading go.mod: %v\n", err)
		os.Exit(1)
	}

	pkgDirs, err := collectPackageDirs(absAPIDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "metrics-gen: walking api-dir: %v\n", err)
		os.Exit(1)
	}

	// Load all packages into a cache so cross-package type resolution can follow
	// field types across package boundaries.
	pkgCache, err := buildPackageInfos(pkgDirs, absAPIDir, subModulePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "metrics-gen: building package cache: %v\n", err)
		os.Exit(1)
	}

	tmpl := template.Must(template.New("metrics").Parse(fileTemplate))

	for _, pkgDir := range pkgDirs {
		info := pkgCache[pkgDir]

		markers := findMarkersInPackage(info)
		if len(markers) == 0 {
			continue
		}

		typePkgAlias := pkgAliasFromImport(info.importPath)

		for _, m := range markers {
			condStatusPkg, err := resolveCondStatusPkg(m.ConditionsPath, m.StructName, info, pkgCache, absAPIDir, subModulePath)
			if err != nil {
				fmt.Fprintf(os.Stderr, "metrics-gen: resolving condition status package for %s.%s: %v\n", pkgDir, m.StructName, err)
				os.Exit(1)
			}

			condStatusAlias := pkgAliasFromImport(condStatusPkg.importPath)

			data := templateData{
				ResourceType:       m.ResourceType,
				ConcreteType:       m.StructName,
				ConditionsAccessor: pathToAccessor(m.ConditionsPath),
				TypePkgAlias:       typePkgAlias,
				TypePkgImport:      info.importPath,
				CondStatusAlias:    condStatusAlias,
				CondStatusImport:   condStatusPkg.importPath,
				SamePackage:        info.importPath == condStatusPkg.importPath,
				ConditionStatuses:  condStatusPkg.statuses,
			}

			if err := generateFile(absOutDir, m.ResourceType, data, tmpl); err != nil {
				fmt.Fprintf(os.Stderr, "metrics-gen: generating %s: %v\n", m.ResourceType, err)
				os.Exit(1)
			}
			fmt.Printf("metrics-gen: generated %s/metrics.go\n", filepath.Join(absOutDir, m.ResourceType))
		}
	}
}

// readModulePath extracts the module path from a go.mod file.
func readModulePath(goModPath string) (string, error) {
	f, err := os.Open(goModPath)
	if err != nil {
		return "", err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if mod, ok := strings.CutPrefix(line, "module "); ok {
			return mod, nil
		}
	}
	return "", fmt.Errorf("no module directive found in %s", goModPath)
}

// collectPackageDirs returns all directories under root that contain at least one .go file.
func collectPackageDirs(root string) ([]string, error) {
	seen := map[string]bool{}
	var dirs []string

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(path, ".go") {
			dir := filepath.Dir(path)
			if !seen[dir] {
				seen[dir] = true
				dirs = append(dirs, dir)
			}
		}
		return nil
	})
	return dirs, err
}

// buildPackageInfos loads a packageInfo for every directory in pkgDirs.
func buildPackageInfos(pkgDirs []string, absAPIDir, subModulePath string) (map[string]*packageInfo, error) {
	cache := make(map[string]*packageInfo, len(pkgDirs))
	for _, dir := range pkgDirs {
		rel, err := filepath.Rel(absAPIDir, dir)
		if err != nil {
			return nil, err
		}
		importPath := subModulePath + "/" + filepath.ToSlash(rel)
		info, err := loadPackageInfo(dir, importPath)
		if err != nil {
			return nil, fmt.Errorf("loading package %s: %w", dir, err)
		}
		cache[dir] = info
	}
	return cache, nil
}

// loadPackageInfo parses all .go files in dir and builds import/type/status maps.
func loadPackageInfo(dir, importPath string) (*packageInfo, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	fset := token.NewFileSet()
	info := &packageInfo{
		dir:        dir,
		importPath: importPath,
		imports:    make(map[string]string),
		types:      make(map[string]*ast.StructType),
	}

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		path := filepath.Join(dir, e.Name())
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil, fmt.Errorf("parsing %s: %w", path, err)
		}
		info.files = append(info.files, file)

		// Collect import aliases from every import spec in this file.
		for _, imp := range file.Imports {
			p := strings.Trim(imp.Path.Value, `"`)
			var alias string
			if imp.Name != nil {
				alias = imp.Name.Name
			} else {
				parts := strings.Split(p, "/")
				alias = parts[len(parts)-1]
			}
			info.imports[alias] = p
		}

		// Collect struct types and ConditionStatus constants.
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			switch gd.Tok {
			case token.TYPE:
				for _, spec := range gd.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					if st, ok := ts.Type.(*ast.StructType); ok {
						info.types[ts.Name.Name] = st
					}
				}
			case token.CONST:
				for _, spec := range gd.Specs {
					vs, ok := spec.(*ast.ValueSpec)
					if !ok {
						continue
					}
					ident, ok := vs.Type.(*ast.Ident)
					if !ok || ident.Name != "ConditionStatus" {
						continue
					}
					for _, name := range vs.Names {
						info.statuses = append(info.statuses, name.Name)
					}
				}
			}
		}
	}

	return info, nil
}

// findMarkersInPackage scans all AST files in info for +metrics:conditions: markers.
func findMarkersInPackage(info *packageInfo) []markerInfo {
	var markers []markerInfo
	for _, file := range info.files {
		for i, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			var prevEnd token.Pos
			if i > 0 {
				prevEnd = file.Decls[i-1].End()
			}
			condPath, resourceType := markerInRange(file.Comments, prevEnd, gd.Pos())
			if resourceType == "" {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				markers = append(markers, markerInfo{
					ResourceType:   resourceType,
					StructName:     ts.Name.Name,
					ConditionsPath: condPath,
				})
			}
		}
	}
	return markers
}

// markerInRange searches all comment groups whose start position falls in
// (prevEnd, typePos) for the +metrics:conditions: marker.
func markerInRange(comments []*ast.CommentGroup, prevEnd, typePos token.Pos) (condPath, resourceType string) {
	for _, cg := range comments {
		if cg.Pos() <= prevEnd || cg.Pos() >= typePos {
			continue
		}
		for _, c := range cg.List {
			text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
			if body, ok := strings.CutPrefix(text, markerPrefix); ok {
				condPath, resourceType = parseMarker(body)
				return
			}
		}
	}
	return
}

// parseMarker parses "path=.status.conditions,resourceType=prometheus" into its components.
func parseMarker(body string) (condPath, resourceType string) {
	for part := range strings.SplitSeq(body, ",") {
		k, v, ok := strings.Cut(part, "=")
		if !ok {
			continue
		}
		switch strings.TrimSpace(k) {
		case "path":
			condPath = strings.TrimSpace(v)
		case "resourceType":
			resourceType = strings.TrimSpace(v)
		}
	}
	return
}

// resolveCondStatusPkg follows each segment of path from startTypeName in startPkg,
// crossing package boundaries as needed, and returns the packageInfo that defines
// the ConditionStatus type (i.e. the package of the slice element type at the end of path).
func resolveCondStatusPkg(path, startTypeName string, startPkg *packageInfo, cache map[string]*packageInfo, absAPIDir, subModulePath string) (*packageInfo, error) {
	segments := strings.Split(strings.TrimPrefix(path, "."), ".")

	curPkg := startPkg
	curTypeName := startTypeName

	for _, seg := range segments {
		// Title-case the segment to match the Go field name (e.g. "status" → "Status").
		fieldName := strings.ToUpper(seg[:1]) + seg[1:]

		st, ok := curPkg.types[curTypeName]
		if !ok {
			return nil, fmt.Errorf("type %s not found in %s", curTypeName, curPkg.dir)
		}

		fieldExpr := findFieldByName(st, fieldName)
		if fieldExpr == nil {
			return nil, fmt.Errorf("field %s not found in type %s (%s)", fieldName, curTypeName, curPkg.dir)
		}

		// Unwrap slice/array to get the element type.
		if arr, ok := fieldExpr.(*ast.ArrayType); ok {
			fieldExpr = arr.Elt
		}

		// Resolve the (element) type to determine the package.
		switch t := fieldExpr.(type) {
		case *ast.Ident:
			// Bare type name: local to the current package.
			curTypeName = t.Name
		case *ast.SelectorExpr:
			// Qualified type: alias.TypeName — cross-package reference.
			alias, ok := t.X.(*ast.Ident)
			if !ok {
				return nil, fmt.Errorf("unexpected selector expression in field %s of %s", fieldName, curTypeName)
			}
			importPath, ok := curPkg.imports[alias.Name]
			if !ok {
				return nil, fmt.Errorf("import alias %q not found in package %s", alias.Name, curPkg.dir)
			}
			nextDir, err := importPathToDir(importPath, absAPIDir, subModulePath)
			if err != nil {
				return nil, fmt.Errorf("resolving import %s: %w", importPath, err)
			}
			nextPkg, ok := cache[nextDir]
			if !ok {
				return nil, fmt.Errorf("package dir %s not in cache (import: %s)", nextDir, importPath)
			}
			curPkg = nextPkg
			curTypeName = t.Sel.Name
		default:
			return nil, fmt.Errorf("unsupported type %T for field %s in %s", fieldExpr, fieldName, curTypeName)
		}
	}

	// curPkg is the package that defines the element type of the conditions slice.
	// ConditionStatus is defined in the same package.
	return curPkg, nil
}

// findFieldByName returns the field type expression for the named field in st, or nil.
func findFieldByName(st *ast.StructType, name string) ast.Expr {
	for _, field := range st.Fields.List {
		for _, n := range field.Names {
			if n.Name == name {
				return field.Type
			}
		}
	}
	return nil
}

// importPathToDir converts an import path to its absolute directory under absAPIDir.
// Only works for packages within the same sub-module.
func importPathToDir(importPath, absAPIDir, subModulePath string) (string, error) {
	rel, ok := strings.CutPrefix(importPath, subModulePath+"/")
	if !ok {
		return "", fmt.Errorf("import %s is outside the API module %s", importPath, subModulePath)
	}
	return filepath.Join(absAPIDir, rel), nil
}

// pkgAliasFromImport derives an import alias from the last two path components,
// e.g. "github.com/.../monitoring/v1" → "monitoringv1".
func pkgAliasFromImport(importPath string) string {
	parts := strings.Split(importPath, "/")
	return strings.Join(parts[max(0, len(parts)-2):], "")
}

// pathToAccessor converts a dot-notation path like ".status.conditions" to a
// Go field accessor like "Status.Conditions".
func pathToAccessor(path string) string {
	parts := strings.Split(strings.TrimPrefix(path, "."), ".")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, ".")
}

// generateFile renders the template and writes the output file.
func generateFile(outDir, resourceType string, data templateData, tmpl *template.Template) error {
	destDir := filepath.Join(outDir, resourceType)
	if err := os.MkdirAll(destDir, 0755); err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("template execution: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt: %w\n--- source ---\n%s", err, buf.String())
	}

	return os.WriteFile(filepath.Join(destDir, "metrics.go"), formatted, 0644)
}
